### ISSUE TITLE
⚠ WARN: Check if each glyph has the recommended amount of contours.

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/FrancoisOne-Font#4]
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: dcroat	Contours detected: 3	Expected: 2
Glyph name: eogonek	Contours detected: 3	Expected: 2
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: uni01B6	Contours detected: 2	Expected: 1
Glyph name: uni01E5	Contours detected: 3	Expected: 2
Glyph name: uni01EA	Contours detected: 3	Expected: 2
Glyph name: uni01EB	Contours detected: 3	Expected: 2
Glyph name: uni01EC	Contours detected: 4	Expected: 3
Glyph name: uni01ED	Contours detected: 4	Expected: 3
Glyph name: uni01F5	Contours detected: 4	Expected: 3
Glyph name: uni0228	Contours detected: 2	Expected: 1
Glyph name: uni0229	Contours detected: 3	Expected: 2
Glyph name: uni023A	Contours detected: 2	Expected: 3
Glyph name: uni023D	Contours detected: 2	Expected: 1
Glyph name: uni023E	Contours detected: 1	Expected: 2
Glyph name: uni0247	Contours detected: 2	Expected: 4
Glyph name: uni1E08	Contours detected: 3	Expected: 2
Glyph name: uni1E09	Contours detected: 3	Expected: 2
Glyph name: uni1E1C	Contours detected: 3	Expected: 2
Glyph name: uni1E1D	Contours detected: 4	Expected: 3
Glyph name: uni20A6	Contours detected: 4	Expected: 1, 3 or 5
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: dcroat	Contours detected: 3	Expected: 2
Glyph name: eogonek	Contours detected: 3	Expected: 2
Glyph name: fi	Contours detected: 2	Expected: 3
Glyph name: uni01B6	Contours detected: 2	Expected: 1
Glyph name: uni01E5	Contours detected: 3	Expected: 2
Glyph name: uni01EC	Contours detected: 4	Expected: 3
Glyph name: uni01ED	Contours detected: 4	Expected: 3
Glyph name: uni0228	Contours detected: 2	Expected: 1
Glyph name: uni0229	Contours detected: 3	Expected: 2
Glyph name: uni023A	Contours detected: 2	Expected: 3
Glyph name: uni023D	Contours detected: 2	Expected: 1
Glyph name: uni023E	Contours detected: 1	Expected: 2
Glyph name: uni0247	Contours detected: 2	Expected: 4
Glyph name: uni1E08	Contours detected: 3	Expected: 2
Glyph name: uni1E09	Contours detected: 3	Expected: 2
Glyph name: uni1E1C	Contours detected: 3	Expected: 2
Glyph name: uni1E1D	Contours detected: 4	Expected: 3
Glyph name: uni20A6	Contours detected: 4	Expected: 1, 3 or 5
Glyph name: uogonek	Contours detected: 2	Expected: 1 [code: contour-count]

</details>

**Comment by rfuenzalida** [comment]
Everything's ok on this part.
