### ISSUE TITLE
⚠ WARN: Do any segments have colinear vectors?

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/FrancoisOne-Font#6]
<details>
<summary>⚠ <b>WARN:</b> Do any segments have colinear vectors?</summary>

* [com.google.fonts/check/outline_colinear_vectors](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors)
<pre>--- Rationale ---

This test looks for consecutive line segments which have the same angle. This
normally happens if an outline point has been added by accident.

This test is not run for variable fonts, as they may legitimately have colinear
vectors.

</pre>

* ⚠ **WARN** The following glyphs have colinear vectors:
	* M: L<<183.0,574.0>--<187.0,516.0>> -> L<<187.0,516.0>--<187.0,0.0>>
	* M: L<<567.0,0.0>--<567.0,520.0>> -> L<<567.0,520.0>--<571.0,574.0>>
	* exclam.sc: L<<85.0,229.0>--<72.0,408.0>> -> L<<72.0,408.0>--<72.0,600.0>>
	* exclam: L<<85.0,229.0>--<72.0,449.0>> -> L<<72.0,449.0>--<72.0,750.0>>
	* exclamdown.sc: L<<190.0,371.0>--<203.0,192.0>> -> L<<203.0,192.0>--<203.0,0.0>>
	* exclamdown: L<<190.0,522.0>--<203.0,302.0>> -> L<<203.0,302.0>--<203.0,1.0>>
	* m.sc: L<<169.0,475.0>--<174.0,363.0>> -> L<<174.0,363.0>--<174.0,0.0>>
	* m.sc: L<<495.0,0.0>--<495.0,362.0>> -> L<<495.0,362.0>--<500.0,484.0>>
	* uni019C: L<<578.0,6.0>--<578.0,138.0>> -> L<<578.0,138.0>--<578.0,141.0>>
	* uni01C3: L<<85.0,229.0>--<72.0,449.0>> -> L<<72.0,449.0>--<72.0,750.0>> and 10 more. [code: found-colinear-vectors]

</details>

**Comment by rfuenzalida** [comment]
Found drawing bugs on ".notdef" and "zero.zero" characters and fixed them.
