### ISSUE TITLE
⚠ WARN: Do outlines contain any jaggy segments?

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/FrancoisOne-Font#7]
<details>
<summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments?</summary>

* [com.google.fonts/check/outline_jaggy_segments](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments)
<pre>--- Rationale ---

This test heuristically detects outline segments which form a particularly
small angle, indicative of an outline error. This may cause false positives in
cases such as extreme ink traps, so should be regarded as advisory and backed
up by manual inspection.

</pre>

* ⚠ **WARN** The following glyphs have jaggy segments:
	* M.001: L<<575.0,0.0>--<575.0,563.0>>/L<<575.0,563.0>--<437.0,0.0>> = 13.772540905391546
	* M.002: L<<343.0,-3.0>--<182.0,554.0>>/L<<182.0,554.0>--<190.0,507.0>> = 6.461964035138681
	* M.002: L<<577.0,509.0>--<584.0,554.0>>/L<<584.0,554.0>--<442.0,9.0>> = 5.761939602397338
	* M.ori: L<<572.0,-6.0>--<572.0,557.0>>/L<<572.0,557.0>--<432.0,0.0>> = 14.108830987596546
	* M: L<<332.0,-4.0>--<183.0,574.0>>/L<<183.0,574.0>--<187.0,516.0>> = 10.510116824925309
	* M: L<<567.0,520.0>--<571.0,574.0>>/L<<571.0,574.0>--<432.0,8.0>> = 9.561415673565511
	* eng: L<<184.0,564.0>--<184.0,440.0>>/B<<184.0,440.0>-<199.0,509.0>-<240.0,541.0>> = 12.2647737278924
	* eth: B<<273.0,545.5>-<298.0,520.0>-<312.0,479.0>>/B<<312.0,479.0>-<303.0,512.0>-<283.5,549.0>> = 3.5980400613611523
	* m.sc: L<<285.0,-3.0>--<169.0,475.0>>/L<<169.0,475.0>--<174.0,363.0>> = 11.084566677713058
	* m.sc: L<<495.0,362.0>--<500.0,484.0>>/L<<500.0,484.0>--<392.0,7.0>> = 10.410657868389393 and 48 more. [code: found-jaggy-segments]

</details>

**Comment by rfuenzalida** [comment]
I did the visual revision for this warn while running Fontbakery, everything looked ok on my side.
